### ISSUE TITLE
Error while running http server

### ISSUE THREAD

**Issue by gr8nishan** [ashwan1/django-deepspeech-server#6]
Hi when i try to run python manage.py runserver 0.0.0.0:8000 i get the below error.  

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fdcbd9b8c80>
Traceback (most recent call last):
  File "/home/hdpuser/anaconda3/lib/python3.6/site-packages/channels/routing.py", line 32, in get_default_application
    value = getattr(module, name)
AttributeError: module 'SpeechServer.asgi' has no attribute 'application'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hdpuser/anaconda3/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/hdpuser/anaconda3/lib/python3.6/site-packages/channels/management/commands/runserver.py", line 81, in inner_run
    application=self.get_application(options),
  File "/home/hdpuser/anaconda3/lib/python3.6/site-packages/channels/management/commands/runserver.py", line 107, in get_application
    return StaticFilesWrapper(get_default_application())
  File "/home/hdpuser/anaconda3/lib/python3.6/site-packages/channels/routing.py", line 28, in get_default_application
    module = importlib.import_module(path)
  File "/home/hdpuser/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/hdpuser/django-deepspeech-server-master/SpeechServer/asgi.py", line 12, in <module>
    application = get_default_application()
  File "/home/hdpuser/anaconda3/lib/python3.6/site-packages/channels/routing.py", line 34, in get_default_application
    raise ImproperlyConfigured("Cannot find %r in ASGI_APPLICATION module %s" % (name, path))
django.core.exceptions.ImproperlyConfigured: Cannot find 'application' in ASGI_APPLICATION module SpeechServer.asgi

```

**Comment by ashwan1** [comment]
Can you please provide channels version.

**Comment by ashwan1** [comment]
Most probable reason might be channels version greater than 2.0.0. For now can you please remove channels package from your installation and install channels==1.1.8 and check. Mean while I'll update my code for channels 2.0.0 and above.

**Comment by gr8nishan** [comment]
Thanks it worked :)
