### ISSUE TITLE
No matching distribution found for Django==2.0.1 (from -r django-deepspeech-server/requirements.txt (line 2) 

### ISSUE THREAD

**Issue by arunimathappa** [ashwan1/django-deepspeech-server#8]
hye, i am trying to run the following command 
**pip install -r data/django-deepspeech-server/requirements.txt**
and i am getting the following error
Collecting appdirs>=1.4.3 (from -r django-deepspeech-server/requirements.txt (line 1))
  Using cached appdirs-1.4.3-py2.py3-none-any.whl
Collecting Django==2.0.1 (from -r django-deepspeech-server/requirements.txt (line 2))
  Could not find a version that satisfies the requirement Django==2.0.1 (from -r django-deepspeech-server/requirements.txt (line 2)) (from versions: 1.1.3, 1.1.4, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.4.18, 1.4.19, 1.4.20, 1.4.21, 1.4.22, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.6.11, 1.7, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.10, 1.7.11, 1.8a1, 1.8b1, 1.8b2, 1.8rc1, 1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9, 1.8.10, 1.8.11, 1.8.12, 1.8.13, 1.8.14, 1.8.15, 1.8.16, 1.8.17, 1.8.18, 1.8.19, 1.9a1, 1.9b1, 1.9rc1, 1.9rc2, 1.9, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8, 1.9.9, 1.9.10, 1.9.11, 1.9.12, 1.9.13, 1.10a1, 1.10b1, 1.10rc1, 1.10, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.10.5, 1.10.6, 1.10.7, 1.10.8, 1.11a1, 1.11b1, 1.11rc1, 1.11, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.11.5, 1.11.6, 1.11.7, 1.11.8, 1.11.9, 1.11.10, 1.11.11, 1.11.12)
**No matching distribution found for Django==2.0.1 (from -r django-deepspeech-server/requirements.txt (line 2))**

could u please tell me what am i doing wrong
my python version is 3.6
linux distribution

**Comment by ashwan1** [comment]
Please try:
**pip3 install -r path/to/django-deepspeech-server/requirements.txt**
instead of pip.

**Comment by arunimathappa** [comment]
my python is by default 3.6 version and so is the pip

**Comment by ashwan1** [comment]
Can you share linux distro info?

**Comment by arunimathappa** [comment]
LINUX VM (RHEL 7) with 8 CPU’s, 8 GB RAM and 300 GB storage

**Comment by ashwan1** [comment]
Please share result of:
**pip --version** and 
**pip3 --version**
command.

**Comment by arunimathappa** [comment]
for pip --version 
pip 9.0.3 from /usr/local/lib/python3.6/site-packages (python 3.6)
for pip3 --version
pip 9.0.3 from /usr/local/lib/python3.6/site-packages (python 3.6)

**Comment by ashwan1** [comment]
We are pretty sure that django==2.0.1 exists. So only reason I can think right now is some version mismatches. I will check more once I set up my RHEL VM. Mean while please make sure that
**python --version** gives you 3.6.x and try running **pip install django==2.0.1** directly.

**Comment by arunimathappa** [comment]
**python version is Python 3.6.4**
but while **pip install django==2.0.1** command gives the same error mentioned above
also i tried to make some changes in requirements.txt and made 
**Django==1.11.12**
but now when i run the **python manage.py runserver** command 
it gives me the following error
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    ) from exc
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

**Comment by ashwan1** [comment]
django 1.11.12 will not work, this project requires django 2.0 and above only

**Comment by arunimathappa** [comment]
that problem is fixed, i am able to start web server and go to **http://127.0.0.1:8000/dsserver/**  this page . but when i browse for audio and ask it to convert 
the result shows **failed** 
Channel layer default (asgiref.inmemory.ChannelLayer)
Quit the server with CONTROL-C.
2018-04-03 09:56:02,004 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2018-04-03 09:56:02,005 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2018-04-03 09:56:02,005 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2018-04-03 09:56:02,005 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2018-04-03 09:56:02,006 - INFO - server - HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2018-04-03 09:56:02,006 - INFO - server - Using busy-loop synchronous mode on channel layer
2018-04-03 09:56:02,007 - INFO - server - Listening on endpoint tcp:port=8000:interface=127.0.0.1
[2018/04/03 09:56:07] HTTP GET /dsserver/ 200 [0.01, 127.0.0.1:50788]
inside module
[2018/04/03 09:58:04] HTTP POST /dsserver/handleaudio/ 200 [0.05, 127.0.0.1:50798]
[2018/04/03 09:58:08] HTTP POST /dsserver/handleaudio/ 200 [0.05, 127.0.0.1:50798]
[2018/04/03 09:58:17] HTTP POST /dsserver/handleaudio/ 200 [0.03, 127.0.0.1:50798]
[2018/04/03 09:58:43] HTTP POST /dsserver/handleaudio/ 200 [0.02, 127.0.0.1:50798]
[2018/04/03 09:58:44] HTTP POST /dsserver/handleaudio/ 200 [0.05, 127.0.0.1:50798]
[2018/04/03 09:58:45] HTTP POST /dsserver/handleaudio/ 200 [0.05, 127.0.0.1:50798]
[2018/04/03 09:58:46] HTTP POST /dsserver/handleaudio/ 200 [0.05, 127.0.0.1:50798]
[2018/04/03 09:58:47] HTTP POST /dsserver/handleaudio/ 200 [0.05, 127.0.0.1:50798]
this is what is showing
can you tell me where i am wrong

**Comment by ashwan1** [comment]
Have you changed  django-deepspeech-server/speech_server_main/config/config.json
as per your requirements?

**Comment by ashwan1** [comment]
And just because of curiosity, may I know what was the problem and how was it resolved?

**Comment by arunimathappa** [comment]
talking of before , i again changed requirements.txt as it was earlier andthen tried it , and surprisingly it worked this time.
but i am when i am passing audio it is showing failed , and yes i did changes in config.json as per my requirement

**Comment by arunimathappa** [comment]
also its is showing some error occured while recording audio stream

**Comment by ashwan1** [comment]
@arunimathappa if issue still persists, please do git pull to get latest code as I have added debug mode. Then try and report logs generated in logs/deepspeech_server.log file.

**Comment by vikasvmads** [comment]
https://stackoverflow.com/questions/48932445/cant-install-django-2-0-by-pip

Please check the above question. I hope you will get some help.

**Comment by Hira-anwar19** [comment]
hey, i need a pair of third eye. kindly someone tell me why i am not able to install django-filters ==0.2.1 this is my error below.

Collecting django-filter==2.2.0
  Using cached django_filter-2.2.0-py3-none-any.whl (69 kB)
ERROR: Could not find a version that satisfies the requirement django-filters==0.2.1 (from versions: none)
ERROR: No matching distribution found for django-filters==0.2.1
